# Generated by Django 5.2.5 on 2026-01-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhanceddata',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', help_text='Status of the enhancement process', max_length=20),
        ),
        migrations.AlterField(
            model_name='enhanceddata',
            name='data',
            field=models.JSONField(default=list, help_text='Array of objects representing the enhanced data'),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
