# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_enhanceddata_status_alter_enhanceddata_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaldata',
            name='schema',
            field=models.JSONField(blank=True, default=dict, help_text="Schema definition mapping field names to types (e.g., {'id': 'int', 'name': 'str'})", null=True),
        ),
    ]
