/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/enhanced-data/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["enhanced_data_list"];
        put?: never;
        post: operations["enhanced_data_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enhanced-data/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["enhanced_data_retrieve"];
        put: operations["enhanced_data_update"];
        post?: never;
        delete: operations["enhanced_data_destroy"];
        options?: never;
        head?: never;
        patch: operations["enhanced_data_partial_update"];
        trace?: never;
    };
    "/api/enhanced-data/enhance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enhanced_data_enhance_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/original-data/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["original_data_list"];
        put?: never;
        post: operations["original_data_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/original-data/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["original_data_retrieve"];
        put: operations["original_data_update"];
        post?: never;
        delete: operations["original_data_destroy"];
        options?: never;
        head?: never;
        patch: operations["original_data_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EnhancedData: {
            readonly id: number;
            /** @description Array of objects representing the enhanced data */
            data?: unknown;
            /**
             * @description Status of the enhancement process
             *
             *     * `pending` - Pending
             *     * `complete` - Complete
             *     * `failed` - Failed
             */
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            original_data: number;
        };
        OriginalData: {
            readonly id: number;
            data?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PatchedEnhancedData: {
            readonly id?: number;
            /** @description Array of objects representing the enhanced data */
            data?: unknown;
            /**
             * @description Status of the enhancement process
             *
             *     * `pending` - Pending
             *     * `complete` - Complete
             *     * `failed` - Failed
             */
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            original_data?: number;
        };
        PatchedOriginalData: {
            readonly id?: number;
            data?: unknown;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `complete` - Complete
         *     * `failed` - Failed
         * @enum {string}
         */
        StatusEnum: "pending" | "complete" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    enhanced_data_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhancedData"][];
                };
            };
        };
    };
    enhanced_data_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnhancedData"];
                "application/x-www-form-urlencoded": components["schemas"]["EnhancedData"];
                "multipart/form-data": components["schemas"]["EnhancedData"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhancedData"];
                };
            };
        };
    };
    enhanced_data_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this enhanced data. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhancedData"];
                };
            };
        };
    };
    enhanced_data_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this enhanced data. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnhancedData"];
                "application/x-www-form-urlencoded": components["schemas"]["EnhancedData"];
                "multipart/form-data": components["schemas"]["EnhancedData"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhancedData"];
                };
            };
        };
    };
    enhanced_data_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this enhanced data. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enhanced_data_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this enhanced data. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEnhancedData"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEnhancedData"];
                "multipart/form-data": components["schemas"]["PatchedEnhancedData"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhancedData"];
                };
            };
        };
    };
    enhanced_data_enhance_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnhancedData"];
                "application/x-www-form-urlencoded": components["schemas"]["EnhancedData"];
                "multipart/form-data": components["schemas"]["EnhancedData"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhancedData"];
                };
            };
        };
    };
    original_data_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginalData"][];
                };
            };
        };
    };
    original_data_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OriginalData"];
                "application/x-www-form-urlencoded": components["schemas"]["OriginalData"];
                "multipart/form-data": components["schemas"]["OriginalData"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginalData"];
                };
            };
        };
    };
    original_data_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this original data. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginalData"];
                };
            };
        };
    };
    original_data_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this original data. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OriginalData"];
                "application/x-www-form-urlencoded": components["schemas"]["OriginalData"];
                "multipart/form-data": components["schemas"]["OriginalData"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginalData"];
                };
            };
        };
    };
    original_data_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this original data. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    original_data_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this original data. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOriginalData"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOriginalData"];
                "multipart/form-data": components["schemas"]["PatchedOriginalData"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginalData"];
                };
            };
        };
    };
}
